bot:
  token: Ваш токин бота
  prefix: /
  embedColor: 0x8c4bc9
  guild: ID Discord сервера
  adminRole: ID Роли для выполнение команд администрирования
  event_birthday: true #Нужны ли вам функции связанные в датой рождения
db:
  host: localhost
  login: root
  password: password
  database: bot
server_ping:
  enabled: true
  ipServer: localhost:25565 #Поддерживаются домены с SRV записью
rcon:
  host: localhost
  port: 25575
  password: password
web:
  avatardir: ./avatar
  skindir: ./skins
  capedir: ./capes
  url: http://localhost:8123
  host: localhost
  port: 8123
  defaultAvatar: ./defaults/avatar.png
  defaultSkin: ./defaults/skin.png
  defaultCape: ./defaults/cape.png
  url_launcher_exe: http://localhost:9274/Launcher.exe
  url_launcher_jar: http://localhost:9274/Launcher.jar